import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MASSJ -Daloa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue dans la <a href="">MASSJ</a>
        </h1>
        <h3>
            <a href="">M</a>utuelle des <a href="">A</a>nciens <a href="">S</a>couts de <a href="">S</a>aint <a href="">J</a>oseph - Daloa
        </h3>

      </main>

    </div>
  )
}

export default Home
